import Head from 'next/head'
import { useEffect, useState } from "react";
import { getAuth, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import fb from '../firebase/clientApp';
import { useAuthState } from 'react-firebase-hooks/auth';
import Image from 'next/image'
import MainAppbar from '../components/mainAppbar'
import Map, {Popup, GeolocateControl, NavigationControl} from 'react-map-gl';

const auth = getAuth(fb)

const TOKEN = "pk.eyJ1IjoicmFodWxrcmlzaG5hIiwiYSI6ImNreW83YnVobDBhdnYyb24yM2hhMGkyb2wifQ.JpccIkRnd-J96QgqrmYsxg";

export default function BuyLand() {
    const [pageIsMounted, setPageIsMounted] = useState(false);
  const [user, loading, error] = useAuthState(auth);
  const [showPopup, setShowPopup] = useState(true);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainAppbar />
      {loading && (<div>loading...</div>)}
      <Map
    initialViewState={{
      longitude: -100,
      latitude: 40,
      zoom: 14
      
    }}
    style={{width: '100%', height: 400}}
    showTileBoundaries= "true"
    mapStyle="mapbox://styles/rahulkrishna/ckyoa46df2way14pek0hja5a6"
    mapboxAccessToken={TOKEN}
    >
      {showPopup && (
      <Popup longitude={-100} latitude={40}
        anchor="bottom"
        onClose={() => setShowPopup(false)}>
        You are here
      </Popup>)}
      <GeolocateControl />
      <NavigationControl />
    </Map>
      
    </div>
  )
}