import Head from 'next/head'
import { useEffect } from 'react'
import { getAuth, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import fb from '../firebase/clientApp';
import { useAuthState } from 'react-firebase-hooks/auth';
import Image from 'next/image'
import MainAppbar from '../components/mainAppbar'

const auth = getAuth(fb)

export default function Support() {
  const [user, loading, error] = useAuthState(auth);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainAppbar />
      {loading && (<div>loading...</div>)}
      {user ? user.name : "not authenticated"}

    </div>
  )
}
